### ISSUE TITLE
运行后找不到ss界面

### ISSUE THREAD

**Issue by drizztz** [joname1/hiwifi-ss#11]
极路由3，界面和截图不同。安装完成之后仍然找不到ss
求更新
![11112222](https://cloud.githubusercontent.com/assets/1671076/26522096/c4314a54-432b-11e7-9db1-89ad6ffdf491.png)

**Comment by joname1** [comment]
貌似是你用错版本了!

1.0xx版本的就用[hiwifi-ss-v1](https://github.com/joname1/hiwifi-ss-v1/blob/master/README.md)
1.2xx以上的请看[#4](https://github.com/joname1/hiwifi-ss-v1/issues/4)
