### ISSUE TITLE
全局模式貌似不太好用？

### ISSUE THREAD

**Issue by hugo-mustang** [joname1/hiwifi-ss#2]
如题
HC5761 - 0.9018.1.12294s

**Comment by joname1** [comment]
@hugoecho 你要了解全局代理的概念, 毕竟geoip_CN也是要走SS的, 你觉得会好用么?

**Comment by hugo-mustang** [comment]
@joname1 不好意思，我没表述清楚。全局模式下我这里显示运行中未加速，智能模式就可以正常使用（运行中已加速）。

**Comment by hugoecho** [comment]
@

**Comment by joname1** [comment]
@hugoecho 未加速只是不启用加速DNS而已, 不影响效果, 建议你使用智能模式: 被墙的网站走SS, 其他则直连.

**Comment by hugo-mustang** [comment]
@joname1 我这是校园网，所以用的ipv6的ss，想要让所有流量都走ss，但是选全局的时候就什么网站都打不开，智能模式下就没有问题。

**Comment by joname1** [comment]
@hugoecho 既然是PC使用, 那就更加简单了, SS或者SSR.

**Comment by hugo-mustang** [comment]
@joname1 哈哈 我觉得我还是没表述清楚，我是在极路由上用，目的是想要连路由器的设备的所有流量都走hiwifi-ss。通常情况下全局模式应该是可以满足我上述需求的，但是呢自从极路由最近一次更新后，重装完hiwifi-ss，全局模式就用不了（更新前的全局模式是可以用的）。

**Comment by joname1** [comment]
@hugoecho 还原出厂设置, 重新刷SS插件.

**Comment by hugo-mustang** [comment]
@joname1 已经还原好多遍了。。我已经放弃了。。默默的走ipv4的流量就好了
