### ISSUE TITLE
不支持新版本：HC5861 - 1.0.7.13499s 

### ISSUE THREAD

**Issue by Shu-Ji** [joname1/hiwifi-ss#3]
不支持新版本：
系统版本 : HC5861 - 1.0.7.13499s 

安装ss插件之后，后台管理页面看不到ss的配置页面了。

**Comment by joname1** [comment]
@Shu-Ji 请降到0.9018.1.12522s即可使用, 请记得关闭自动升级.

**Comment by Shu-Ji** [comment]
@joname1 
感谢。看了下论坛，降级好像比较麻烦。
最后只能通过修改极路由的view代码，将shadow[和谐]socks的页面植入到页面了。
