### ISSUE TITLE
系统版本 : HC5861 - 0.9018.1.12522s  安装的时候报错 installing error

### ISSUE THREAD

**Issue by huhai586** [joname1/hiwifi-ss#4]
系统版本 : HC5861 - 0.9018.1.12522s  安装的时候报错 installing error
重启后安装一直报这个错...不知道该怎么办，大神有遇到过吗

**Comment by joname1** [comment]
@huhai586 我的也是0.9018.1.12522s, 没有出现问题, 你贴个图看下.

**Comment by huhai586** [comment]
@joname1 后来我再次重置了路由器，然后安装，竟然好了，百思不得其解，不过既然好了，就行啦。谢谢你的回复~
