### ISSUE TITLE
系统版本 : HC5761 - 1.0.7.13499s  

### ISSUE THREAD

**Issue by panw3i** [joname1/hiwifi-ss#5]
系统版本 : HC5761 - 1.0.7.13499s   安装好后在哪里设置？

**Comment by joname1** [comment]
@panw3i [点击打开看截图](http://7xoatu.com1.z0.glb.clouddn.com/o_1af3c0jfl1afp1ehd19m713c58baa.jpg)

**Comment by panw3i** [comment]
这个知道 升级到到新版后 界面改了  高级设置选项也消失了  @joname1

**Comment by joname1** [comment]
@panw3i 目前不支持1.0以上固件, 请降回0.9018.1.12294s,  然后关闭自动升级.
